#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  #only:
  #  - master
  except:
    - README.md
    - .travis.yml

clone_folder: c:\projects\facade
image:
- Visual Studio 2017

configuration:
- Release

platform:
- x64
environment:
  matrix:
  - arch: Win64

init:
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 %arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015 %arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013 %arch%" )
- echo %generator%

before_build:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake --version
- cmake .. -G %generator%
- cd ..

build:
  project: c:\projects\facade\build\facade.sln
  parallel: true


test_script:
  - cmd: build\test\Release\test.exe